name: CI

on:
  - push
  - pull_request

jobs:

  linux:
    name: Linux
    # Includes Mono 6.12 and MSBuild 16.6, from download.mono-project.com/repo/ubuntu (stable-focal).
    # https://github.com/actions/virtual-environments/blob/ubuntu20/20210606.1/images/linux/Ubuntu2004-README.md
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Versions
        run: |
          mono --version
          msbuild /version
      - run: msbuild src/CVTBot.sln /p:Configuration=Release
      - run: msbuild src/CVTBot.sln /p:Configuration=Debug

  macos:
    name: macOS
    # Includes Mono 6.12 and MSBuild 16.6.
    #
    # https://github.com/actions/virtual-environments/blob/macOS-10.15/20210607.1/images/macos/macos-10.15-Readme.md
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3
      - name: Versions
        run: |
          mono --version
          msbuild /version
      - run: msbuild src/CVTBot.sln /p:Configuration=Release
      - run: msbuild src/CVTBot.sln /p:Configuration=Debug
