name: CI

on:
  - push
  - pull_request

jobs:

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Versions
        run: |
          mono --version
          msbuild /version
      - run: msbuild src/CVTBot.sln /p:Configuration=Release
      - run: msbuild src/CVTBot.sln /p:Configuration=Debug

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Versions
        run: |
          mono --version
          msbuild /version
      - run: msbuild src/CVTBot.sln /p:Configuration=Release
      - run: msbuild src/CVTBot.sln /p:Configuration=Debug
