name: CI

on:
  - push
  - pull_request

jobs:

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Versions
        run: dotnet --version
      - run: dotnet build src/CVTBot.sln --configuration=Release
      - run: dotnet build src/CVTBot.sln --configuration=Debug
      - run: cd src/CVTBot/bin/Release/net6.0 && dotnet run --project ../../../CVTBot.csproj --configuration=Debug

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Versions
        run: dotnet --version
      - run: dotnet build src/CVTBot.sln --configuration=Release
      - run: dotnet build src/CVTBot.sln --configuration=Debug
